# Generated by Django 5.2.8 on 2025-11-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('phone', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('technology1', models.CharField(max_length=50)),
                ('technology2', models.CharField(max_length=50)),
            ],
        ),
    ]
